[zh]
  title = "咻咻咻"
  languageName = "中国话"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/zh"

[en]
  title = "LQ"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "이강"
  languageName = "한국어"
  weight = 3
  languagedir = "ltr"
  contentdir = "content/ko"
