# Override these settings with your own
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
baseURL = "https://www.liqiangxo.one/"
copyright = "© {year}"

# The value "hugo-theme-codex" is only to get the exampleSite
# to work in this repo. Change to whatever name you gave the theme
# when you added it. If you followed the README, you should have 
# added the theme using the name "codex".
theme = "codex" 

# REMOVE THIS!
# This is only to get the exampleSite to work in this repo.
# themesDir = "./" 

# Add your Disqus shortname here.
[params.valine]
    enable = true
    appId = '1fVnzL30puihhMql5HS0pwm4-gzGzoHsz'
    appKey = 'kYMC0bQQ0EXTJUJuFMDh2jF7'
    notify = false 
    verify = false 
    avatar = 'mm'
    placeholder = '说点什么吧...'
    visitor = true
paginate = 10
# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "456" 

canonifyurls = true
publishDir = "./liqiangxo"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/liqiangxo"
  github = "https://github.com/liqiangxo"
  email = "mailto:liqiangxo@sina.cn"
  # facebook = "https://facebook.com/<your handle>"
  gitlab = "https://gitlab.com/liqiangxo"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["Twitter", "GitHub", "Email", "GitLab"]

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "a-liqiangxo"
  name = "liqiangxo"
  title = "liqiangxo"
  url = "/"
[[menu.main]]
  identifier = "b-about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "c-coder"
  name = "coder"
  title = "coder"
  url = "/coder"

[[menu.main.js]]
  identifier = "js"
  name = "js"
  title = "js"
  url = "/coder/js"